### ISSUE TITLE
Missing training dataset problem

### ISSUE THREAD

**Issue by rain2050** [APRIL-ZJU/3QNet#1]
Hello, thank you for your excellent open source work. In the process of reproducing your work, I found that there is no training data set, can you provide it? Looking forward to your reply, very grateful.

**Comment by Tianxinhuang** [comment]
Thank you for your attention to our work. As we claimed in the original paper, we train our network based on simple 2048 points models in ShapeNet part dataset. Available data can be found in FoldingNet (http://www.merl.com/research/license#FoldingNet) or AE (https://github.com/optas/latent_3d_points).

**Comment by rain2050** [comment]
Thank you for your reply, I wish you success in your research.
