### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by rain2050** [APRIL-ZJU/3QNet#2]
Thank you for disclosing such an excellent work, but when training again, the program reports the following error, do you know the reason? Looking forward to your reply.

Traceback (most recent call last):
  File "/home/rain/3QNet/qnet.py", line 613, in <module>
    train()
  File "/home/rain/3QNet/qnet.py", line 577, in train
    traindata = traindata[ids, :, :]
IndexError: too many indices for array

**Comment by Tianxinhuang** [comment]
Please check the dimension of your read data. The `datalist` defined in Line 468 should be a list including multiple 2048*2048*3 point clouds for the dataset we adopted.

**Comment by rain2050** [comment]
Thank you for your reply, thanks
